server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: giftify

  profiles:
    group:
      local:
        - app-local
        - core-local
        - payment-local
        - funding-local
        - settlement-local
        - search-local
        - infra-local
        - common-local
      dev:
        - app-dev
        - core-dev
        - payment-dev
        - funding-dev
        - settlement-dev
        - search-dev
        - infra-dev
        - common-dev
      prod:
        - app-prod
        - core-prod
        - payment-prod
        - funding-prod
        - settlement-prod
        - search-prod
        - infra-prod
        - common-prod

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}

custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: giftify.yjkim.store
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "giftify"
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"