server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: giftify

  profiles:
    group:
      local:
        - app-local
        - member-local
        - auth-local
        - search-local
        - product-local
        - funding-local
        - order-local
        - payment-local
        - notification-local
        - common-local
      dev:
        - app-dev
        - member-dev
        - auth-dev
        - search-dev
        - product-dev
        - funding-dev
        - order-dev
        - payment-dev
        - notification-dev
        - common-dev
      prod:
        - app-prod
        - member-prod
        - auth-prod
        - search-prod
        - product-prod
        - funding-prod
        - order-prod
        - payment-prod
        - notification-prod
        - common-prod

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}

custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: giftify.yjkim.store
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "giftify"
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"